name: PDF to HTML Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ libpoppler-cpp-dev libpoppler-glib-dev pkg-config

      - name: Build and install pdf2htmlEX
        run: |
          git clone --depth 1 --branch v0.18.8 https://github.com/coolwanglu/pdf2htmlEX.git
          cd pdf2htmlEX
          cmake .
          make
          sudo make install

      - name: Convert PDF to HTML
        run: |
          for file in $(find . -name "*.pdf"); do
            filename=$(basename "$file")
            filename="${filename%.*}"
            htmlname="$filename.html"
            pdf2htmlEX "$file" "$htmlname"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.html
          git commit -m "Convert PDF to HTML"
          git push
