name: PDF to HTML Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pdf2html
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Remove existing files in docs directory
        run: |
          shopt -s extglob
          rm -rf docs/!(.git)

      - name: Create docs directory
        run: |
          mkdir -p docs

      - name: Create index.html
        run: |
          echo "<html><body><ul>" > docs/index.html
          echo "</ul></body></html>" >> docs/index.html

      - name: Convert PDF to HTML
        run: |
          find . -name "*.pdf" -print0 | while IFS= read -r -d '' file; do
            filename=$(basename "$file" .pdf)
            htmlname="docs/$filename.html"
            pdftohtml -s -c "$file" "$htmlname"
            echo "<li><a href='$filename.html'>$filename</a></li>" >> docs/index.html
          done
          find docs -name "*-html.html" -exec bash -c 'mv "$0" "${0//-html/}"' {} \;

      - name: Generate sitemap.xml
        run: |
          cd docs
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > sitemap.xml
          echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> sitemap.xml
          for file in *.html; do
            filename=$(basename "$file" .html)
            echo "  <url><loc>https://example.com/docs/$filename.html</loc></url>" >> sitemap.xml
          done
          echo "</urlset>" >> sitemap.xml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git ls-files | grep -v "^docs/" | xargs git rm
          git add docs/*.html docs/sitemap.xml
          git add docs/*.png
          git status
          git commit -m "Convert PDF to HTML and generate sitemap"
          git push
