name: PDF to HTML Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pdf2htmlex
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1 libcairo2 libjpeg-turbo8
          wget https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-bionic-x86_64.deb
          sudo mv pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-bionic-x86_64.deb pdf2htmlEX.deb
          sudo apt install ./pdf2htmlEX.deb

      - name: Remove existing HTML files
        run: |
          rm -f docs/*
          
      - name: Convert PDF naar HTML
        run: |
          mkdir docs
          find . -name "*.pdf" | while read filename; do
            html_file="${filename%.*}.html"
            pdf2htmlex "$filename" "$html_file"
            mv "$html_file" docs/
          done

      - name: Create index.html
        run: |
          cd docs
          echo "<html><body><ul>" > index.html
          find . -name "*.html" | while read filename; do
            echo "<li><a href='$filename'>$filename</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Generate sitemap.xml
        run: |
          cd docs
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > sitemap.xml
          echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> sitemap.xml
          for file in *.html; do
            filename=$(basename "$file" .html)
            echo "  <url>" >> sitemap.xml
            echo "    <loc>https://vincentvandijk96.github.io/WOO/$filename.html</loc>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done
          echo "</urlset>" >> sitemap.xml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git add docs/*
          git status
          git commit -m "Convert PDF to HTML and generate sitemap"
          git push
